services:

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=0
      - JAEGER_GRPC_ENABLED=true
      - JAEGER_HTTP_ENABLED=true
      - JAEGER_UDP_ENABLED=false

  otlcollector:
    build:
      context: ./otlcollector
      dockerfile: Dockerfile
    container_name: otlcollector
    ports:
      - "4318:4318"  # OTLP HTTP endpoint
    depends_on:
      - jaeger

  goapp:
    build:
      context: ./goapp
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlcollector:4318
    depends_on:
      - otlcollector
      - netcoreapp

  netcoreapp:
    build:
      context: ./netcoreapp/app-otl
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlcollector:4318
    depends_on:
      - otlcollector
