services:

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP Collector (OTLP over HTTP)
      - "4318:4318"    # OTLP HTTP (for OpenTelemetry SDKs)
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # Enable OTLP HTTP collector
      - COLLECTOR_ZIPKIN_HTTP_PORT=0  # Disable Zipkin
      - JAEGER_GRPC_DISABLED=true  # Disable gRPC receiver
      - JAEGER_HTTP_ENABLED=true  # Enable HTTP collector (ensure this is explicitly enabled)
      - JAEGER_UDP_ENABLED=false  # Disable UDP

  goapp:
    build:
      context: ./goapp
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - netcoreapp


  netcoreapp:
    build:
      context: ./netcoreapp/app-otl
      dockerfile: Dockerfile
    ports:
      - 8080:80
