version: "3.8"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=0
      - JAEGER_GRPC_ENABLED=true
      - JAEGER_HTTP_ENABLED=true
      - JAEGER_UDP_ENABLED=false

  otlcollector:
    build:
      context: ./otlcollector
      dockerfile: Dockerfile
    container_name: otlcollector
    ports:
      - "4318:4318"
    depends_on:
      - jaeger

  payments.subscription:
    build:
      context: ./Payments.Subscription
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      otlcollector:
        condition: service_started

  payments.customer:
    build:
      context: ./Payments.Customer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - otlcollector

  mysql:
    image: mysql:8.0
    container_name: payments-subscription-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: payments_subscription
      MYSQL_USER: payments
      MYSQL_PASSWORD: payments123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Payments.Subscription/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  logs:
    driver: local
  mysql_data:
    driver: local
