services:

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=0
      - JAEGER_GRPC_ENABLED=true
      - JAEGER_HTTP_ENABLED=true
      - JAEGER_UDP_ENABLED=false

  otlcollector:
    build:
      context: ./otlcollector
      dockerfile: Dockerfile
    container_name: otlcollector
    ports:
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./logs:/logs
    depends_on:
      - jaeger
      - loki

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - otlcollector

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
    user: "10001"

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki

  payments.subscription:
    build:
      context: ./Payments.Subscription
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      otlcollector:
        condition: service_started

  payments.customer:
    build:
      context: ./Payments.Customer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - otlcollector

  mysql:
    image: mysql:8.0
    container_name: payments-subscription-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: payments_subscription
      MYSQL_USER: payments
      MYSQL_PASSWORD: payments123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Payments.Subscription/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  logs:
    driver: local
  mysql_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local
