receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

  filelog:
    include: [ "/logs/*.log" ]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: time
          layout: '%Y-%m-%d %H:%M:%S'

processors:
  transform/mask_credit_cards:
    trace_statements:
      - context: span
        statements:
          - replace_pattern(attributes["http.response.body"], "(\\d{4})-(\\d{4})-(\\d{4})-", "xxxx-xxx-xxxx-")
   
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # Exporter para debug (logs)
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # Exporter para o Jaeger via OTLP
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Exporter para Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Exporter para Loki
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "example"
    labels:
      attributes:
        container_name: "service_name"
        level: "severity"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/mask_credit_cards]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [loki, logging] 