server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Keep only containers with subscription or customer in the name
      - source_labels: [__meta_docker_container_name]
        regex: '.*payments\.(subscription|customer).*'
        action: keep

      # Extract service label (subscription or customer) from container name
      - source_labels: [__meta_docker_container_name]
        regex: '.*/fc3-otl-payments\.(customer|subscription)-.*'
        target_label: service
        replacement: '$1'

      # Add static category label
      - target_label: category
        replacement: app

      # Add static job label
      - target_label: job
        replacement: app

    pipeline_stages:
      # Extract app_service from logs like "[subscription]" or "[customer]"
      - regex:
          expression: '.*\[(?P<app_service>subscription|customer)\].*'
          source: __line__

      # Extract correlat
