server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - target_label: job
        replacement: app

    pipeline_stages:
      - json:
          expressions:
            correlation_id: correlation_id
            service: service
            level: level
      - labels:
          correlation_id: correlation_id
          service: service
          level: level
