server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /position/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'apps'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'apps'
          __path__: /logs/apps/*.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            correlation_id: correlation_id
            service: service
      - timestamp:
          source: time
          format: RFC3339Nano


